name = "hn-hrcb-cron"
main = "functions/cron.ts"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "udhr-hrcb"
database_id = "d49c47bc-8107-4481-8aa1-6a9cf0b534c8"

[[kv_namespaces]]
binding = "CONTENT_CACHE"
id = "ffe31e8bd21f43169e81f6d6137772bf"

[triggers]
crons = ["*/5 * * * *"]

[[queues.producers]]
queue = "hrcb-eval-queue"
binding = "EVAL_QUEUE"

# Secrets (set via `wrangler secret put --name hn-hrcb-cron`):
# ANTHROPIC_API_KEY
# CRON_SECRET
