name = "hrcb-enqueue"
main = "scripts/enqueue.ts"
compatibility_date = "2026-02-01"

[[d1_databases]]
binding = "DB"
database_name = "hrcb-db"
database_id = "8d46e768-e02d-421f-93f6-6dfa06a378c5"

[[queues.producers]]
queue = "hrcb-eval-queue"
binding = "EVAL_QUEUE"
